### ISSUE TITLE
Download window doesn't always appear in IE9

### ISSUE THREAD

**Issue by aldefouw** [witstep/response-monitor.js#1]
First off - thank you so much for making this wonderful library.  This is the only library I found that would allow me to easily monitor a download for a submitted form.

The issue that I am having with the library is related to its use in Internet Explorer 9. 

If I initiate a download from the form, downloads are intermittently failing to pop up on screen AFTER the library has done its stuff.  

To be clear: the ResponseMonitor is hitting onRequest, onMonitor, AND, importantly, onResponse beautifully.  I can fire off whatever JS events I want in those callbacks.

The failure is not to display the loading screen mask - the failure is to show the file download dialogue box in the browser.  This of course is a problem - because not getting a download dialogue box is even worse than not seeing a download mask.

I initially thought this problem was related to cookies not expiring, but further investigation revealed it had nothing to do with the cookies and those were working as expected.  

Unfortunately, intermittent behavior is just about the worst behavior to have so I had to get to the bottom of this.

The good news is ... I think I have found a solution.  The bad news is ... I'm not sure if it's safe.

By removing line 191 through 198 of response-monitor.js, I removed the default behavior that apparently stops the download in its tracks.  By removing these lines, the downloads always work beautifully for me in IE9 now.

That said, I am sure there is a very good reason for why this behavior was originally implemented - thus I am nervous to actually use this method.

Do you have any input on why the code to stop downloads is there and whether removing it would be safe?  

Perhaps you can think up a different solution that will work better, but it would be nice for this framework to be fully compatible with IE9 =).

Thanks!
Adam

**Comment by jorgemcpaulo** [comment]
Hi Adam,
I'm glad the library is being useful.
Thanks for reporting issues, it will help make it more robust.

The role of the code you removed is to stop the HTTP request when there's a timeout.
(for example, doesn't make sense to receive the file at 40s if timeout is set for 30s and the user is doing something else and not expecting the file anymore. That would be the only side-effect of removing the code.)

Seems there's a bug in the library code. I think it is intermittent because it depends on which IE9 thread finishes first - the one handling the cookie, or the one handling the download.

This should fix it. Wrap the try/catch block in this condition. It will only stop the request if there was a timeout.
if( this.countdown < 0 ){
   // try/catch...
}

I would like to know if it works for you. If possible also simulate a timeout situation.

When I have the chance, I will commit the fix and generate the minified file.

Thanks,
Jorge

**Comment by aldefouw** [comment]
Hi Jorge - 

Thanks for the suggestions.  I did some tests with your recommended code change in IE9.  

To me, it looks like your conditional wrapper that you suggested is doing what is expected.  

The downloads seemed to work every time in IE9.

I also set the timeout to 1 second and watched through console.log monitoring as the various events (onRequest, onMonitor, etc.) were triggered.  When I had the timeout set to 1 second on a download that should take 5 seconds, onRequest was hit, and onMonitor was hit each second.

The download never happened (which is what should be expected if I am not mistaken).

I think that means that the chunk of code that you wanted me to wrap was still being executed when the timeout counter became less than 0.  Which is what we want, I think?

It looks good to me.  Thanks for all your help.

Kind Regards,
Adam
